name: graph_app
description: A Flutter web app for graphing benchmark results.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.35

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: 0.12.2

  flutter:
    sdk: flutter

  flutter_benchmark_utils:
    path: ../..

dev_dependencies:

flutter:
  uses-material-design: true
