name: flutter_benchmark_utils
description: Flutter package with scripts to graph and analyze Flutter benchmark output
version: 0.0.42
author: flar
homepage: http://github.com/flar/flutter_benchmark_utils

executables:
  graphAB:
  graphDashboard:
  graphTimeline:
  graphMeminfo:

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  archive: ^3.0.0
  args: ^2.0.0
  http: ^0.13.0
  meta: ^1.7.0
  open_url: ^2.0.0-nullsafety
